source 'http://rubygems.org'

gem 'devise'
gem 'foundation-rails'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

group :development do
  gem "sqlite3"
end

gem "minitest-rails"
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

group :test do
  gem "minitest-rails-capybara"
  gem "launchy"
end

group :development do
  gem 'rails_layout'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
