source 'https://rubygems.org'
ruby '2.0.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0'
gem 'spring'
gem 'sqlite3'
gem 'therubyracer'
gem 'this gem', '4.1.1'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :test do
  gem 'launchy'
  gem 'minitest-rails-capybara'
end

group :development, :test do
  gem 'rails_layout'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
